{"name": "Demarrage", "status": "failed", "statusDetails": {"message": "Setup failed:\nWebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not find a connected Android device in 20362ms.\nStacktrace:\nUnknownError: An unknown server-side error occurred while processing the command. Original error: Could not find a connected Android device in 20362ms.\n    at getResponseForW3CError (C:\\Users\\monsh\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\@appium\\base-driver\\lib\\protocol\\errors.js:1073:9)\n    at asyncHandler (C:\\Users\\monsh\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\@appium\\base-driver\\lib\\protocol\\protocol.js:491:57)\n\nAlso teardown failed:\nNo application is open"}, "start": 1689338201067, "stop": 1689338236879, "uuid": "75cd58ab-a552-48c1-8ad4-1e0030437888", "historyId": "84a88efa2949dbb22117d72f5b94008a", "fullName": "Tests.homeTest.Demarrage", "labels": [{"name": "suite", "value": "Tests"}, {"name": "subSuite", "value": "homeTest"}, {"name": "framework", "value": "robotframework"}, {"name": "language", "value": "cpython3"}, {"name": "host", "value": "LAPTOP-KC6KER4Q"}, {"name": "thread", "value": "default-4d0ea8d4-054a-4afc-9b29-585948e98e64"}, {"name": "tag", "value": "test_001"}]}