{"name": "Demarrage", "status": "failed", "statusDetails": {"message": "Setup failed:\nWebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not find a connected Android device in 20194ms.\nStacktrace:\nUnknownError: An unknown server-side error occurred while processing the command. Original error: Could not find a connected Android device in 20194ms.\n    at getResponseForW3CError (C:\\Users\\monsh\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\@appium\\base-driver\\lib\\protocol\\errors.js:1073:9)\n    at asyncHandler (C:\\Users\\monsh\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\@appium\\base-driver\\lib\\protocol\\protocol.js:491:57)\n\nAlso teardown failed:\nNo application is open"}, "start": 1689338107220, "stop": 1689338137954, "uuid": "7820d124-1660-406b-ac93-8ddec0c7521c", "historyId": "84a88efa2949dbb22117d72f5b94008a", "fullName": "Tests.homeTest.Demarrage", "labels": [{"name": "suite", "value": "Tests"}, {"name": "subSuite", "value": "homeTest"}, {"name": "framework", "value": "robotframework"}, {"name": "language", "value": "cpython3"}, {"name": "host", "value": "LAPTOP-KC6KER4Q"}, {"name": "thread", "value": "default-861b9870-d840-4cd8-af1c-eb25b87c406a"}, {"name": "tag", "value": "test_001"}]}