{"name": "Demarrage", "status": "failed", "statusDetails": {"message": "Setup failed:\nWebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not find a connected Android device in 20224ms.\nStacktrace:\nUnknownError: An unknown server-side error occurred while processing the command. Original error: Could not find a connected Android device in 20224ms.\n    at getResponseForW3CError (C:\\Users\\monsh\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\@appium\\base-driver\\lib\\protocol\\errors.js:1073:9)\n    at asyncHandler (C:\\Users\\monsh\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\@appium\\base-driver\\lib\\protocol\\protocol.js:491:57)\n\nAlso teardown failed:\nNo application is open"}, "start": 1689338328167, "stop": 1689338358595, "uuid": "3d00fc6d-c1e8-42cc-89a4-4e98d9ac6d91", "historyId": "84a88efa2949dbb22117d72f5b94008a", "fullName": "Tests.homeTest.Demarrage", "labels": [{"name": "suite", "value": "Tests"}, {"name": "subSuite", "value": "homeTest"}, {"name": "framework", "value": "robotframework"}, {"name": "language", "value": "cpython3"}, {"name": "host", "value": "LAPTOP-KC6KER4Q"}, {"name": "thread", "value": "default-6612bb64-7a17-471d-93ae-a4ff52f9d3f6"}, {"name": "tag", "value": "test_001"}]}